### ISSUE TITLE
💕Register entry?Just stuck in the login page and couldn't get in...😂

### ISSUE THREAD

**Issue by augusttty** [brdebr/aiim#1]

**Comment by brdebr** [comment]
Hello 👋
Sorry for the late answer but was pretty busy IRL 😅

About signing up users: the endpoint is implemented and you can access it in `/api/auth/signup`
But currently I don't have a form for this, you would have to do the peticion "manually".

Also another thing to point out is that for the "signup petition" you also need to provide a special header named "sign-pass" with the value you've configured at the .env file (by default is "cowabunga")

A curl example would be:
```
curl --request POST \
  --url http://127.0.0.1:3005/api/auth/signup \
  --header 'Content-Type: application/json' \
  --header 'sign-pass: cowabunga' \
  --data '{
	"name": "user",
	"email": "user@test.com",
	"password": "thepassword"
}'
```

**Comment by augusttty** [comment]
> Hello 👋 Sorry for the late answer but was pretty busy IRL 😅
> 
> About signing up users: the endpoint is implemented and you can access it in `/api/auth/signup` But currently I don't have a form for this, you would have to do the peticion "manually".
> 
> Also another thing to point out is that for the "signup petition" you also need to provide a special header named "sign-pass" with the value you've configured at the .env file (by default is "cowabunga")
> 
> A curl example would be:
> 
> ```
> curl --request POST \
>   --url http://127.0.0.1:3005/api/auth/signup \
>   --header 'Content-Type: application/json' \
>   --header 'sign-pass: cowabunga' \
>   --data '{
> 	"name": "user",
> 	"email": "user@test.com",
> 	"password": "thepassword"
> }'
> ```

Thanks!I will try 😁
